"""Listas cerradas (verbos-accion, conectores, negaciones, determinantes), en la misma forma que produce `normalize`."""

VERBOS_ACCION: frozenset[str] = frozenset(
    {
        "querer",
        "necesitar",
        "poder",
        "deber",
        "mostrar",
        "ver",
        "consultar",
        "revisar",
        "chequear",
        "decir",
        "explicar",
        "informar",
        "avisar",
        "notificar",
        "alertar",
        "dar",
        "enviar",
        "mandar",
        "compartir",
        "activar",
        "desactivar",
        "encender",
        "apagar",
        "prender",
        "cancelar",
        "confirmar",
        "aceptar",
        "rechazar",
        "ayudar",
        "guiar",
        "comparar",
        "buscar",
        "encontrar",
        "reportar",
        "registrar",
        "cambiar",
        "actualizar",
        "modificar",
        "ajustar",
        "configurar",
        "agregar",
        "añadir",
        "quitar",
        "eliminar",
        "borrar",
        "iniciar",
        "comenzar",
        "empezar",
        "terminar",
        "finalizar",
        "parar",
        "detener",
        "repetir",
        "reintentar",
    }
)

CONECTORES: frozenset[str] = frozenset(
    {
        "y",
        "tambien",
        "ademas",
        "o",
        "pero",
        "sino",
        "aunque",
        "mientras",
        "despues",
        "luego",
        "entonces",
        "aparte",
        "asimismo",
    }
)

NEGACIONES: frozenset[str] = frozenset(
    {
        "no",
        "nunca",
        "jamas",
        "tampoco",
        "ni",
        "nada",
        "ningun",
        "ninguna",
        "ninguno",
    }
)

CONECTORES_COORDINANTES: frozenset[str] = frozenset(
    {
        "y",
        "tambien",
        "ademas",
        "o",
        "pero",
        "sino",
        "aparte",
        "asimismo",
    }
)

DETERMINANTES: frozenset[str] = frozenset(
    {
        "el",
        "la",
        "los",
        "las",
        "un",
        "una",
        "unos",
        "unas",
        "mi",
        "mis",
        "tu",
        "tus",
        "su",
        "sus",
        "este",
        "esta",
        "estos",
        "estas",
        "ese",
        "esa",
        "esos",
        "esas",
        "del",
        "al",
    }
)
