"""Variantes conjugadas de VERBOS_ACCION escritas a mano (imperativo, voseo, "-me", modal en primera persona), no stemming."""

from __future__ import annotations

from intent_router.lexicon import VERBOS_ACCION

VARIANTES_VERBO: dict[str, str] = {
    # querer
    "quiero": "querer",
    "queres": "querer",
    "quisiera": "querer",
    # necesitar
    "necesito": "necesitar",
    # poder
    "puedo": "poder",
    "podes": "poder",
    # deber
    "debo": "deber",
    # mostrar
    "muestra": "mostrar",
    "mostra": "mostrar",
    "muestrame": "mostrar",
    "mostrame": "mostrar",
    # consultar
    "consulta": "consultar",
    "consultame": "consultar",
    # revisar
    "revisa": "revisar",
    "revisame": "revisar",
    # chequear
    "chequea": "chequear",
    "chequeame": "chequear",
    # decir
    "di": "decir",
    "deci": "decir",
    "dime": "decir",
    "decime": "decir",
    "digo": "decir",
    # explicar
    "explica": "explicar",
    "explicame": "explicar",
    # informar
    "informa": "informar",
    "informame": "informar",
    # avisar
    "avisa": "avisar",
    "avisame": "avisar",
    "avises": "avisar",
    # notificar
    "notifica": "notificar",
    "notificame": "notificar",
    # alertar
    "alerta": "alertar",
    "alertame": "alertar",
    # dar
    "da": "dar",
    "dame": "dar",
    "deme": "dar",
    "doy": "dar",
    # enviar
    "envia": "enviar",
    "enviame": "enviar",
    # mandar
    "manda": "mandar",
    "mandame": "mandar",
    "mandes": "mandar",
    # compartir
    "comparte": "compartir",
    "comparti": "compartir",
    "comparteme": "compartir",
    "compartime": "compartir",
    # activar
    "activa": "activar",
    "activame": "activar",
    # desactivar
    "desactiva": "desactivar",
    "desactivame": "desactivar",
    # encender
    "enciende": "encender",
    "encende": "encender",
    "enciendeme": "encender",
    "encendeme": "encender",
    # apagar
    "apaga": "apagar",
    "apagame": "apagar",
    # prender
    "prende": "prender",
    "prendeme": "prender",
    # cancelar
    "cancela": "cancelar",
    "cancelame": "cancelar",
    # confirmar
    "confirma": "confirmar",
    "confirmame": "confirmar",
    # aceptar
    "acepta": "aceptar",
    "aceptame": "aceptar",
    # rechazar
    "rechaza": "rechazar",
    "rechazame": "rechazar",
    # ayudar
    "ayuda": "ayudar",
    "ayudame": "ayudar",
    # guiar
    "guia": "guiar",
    "guiame": "guiar",
    # comparar
    "compara": "comparar",
    "comparame": "comparar",
    # buscar
    "busca": "buscar",
    "buscame": "buscar",
    # encontrar
    "encuentra": "encontrar",
    "encontra": "encontrar",
    # reportar
    "reporta": "reportar",
    "reportame": "reportar",
    # registrar
    "registra": "registrar",
    "registrame": "registrar",
    # cambiar
    "cambia": "cambiar",
    "cambiame": "cambiar",
    # actualizar
    "actualiza": "actualizar",
    "actualizame": "actualizar",
    # modificar
    "modifica": "modificar",
    "modificame": "modificar",
    # ajustar
    "ajusta": "ajustar",
    "ajustame": "ajustar",
    # configurar
    "configura": "configurar",
    "configurame": "configurar",
    # agregar
    "agrega": "agregar",
    "agregame": "agregar",
    # añadir
    "añade": "añadir",
    "añadi": "añadir",
    # quitar
    "quita": "quitar",
    "quitame": "quitar",
    # eliminar
    "elimina": "eliminar",
    "eliminame": "eliminar",
    # borrar
    "borra": "borrar",
    "borrame": "borrar",
    # iniciar
    "inicia": "iniciar",
    # comenzar
    "comienza": "comenzar",
    "comenza": "comenzar",
    # empezar
    "empieza": "empezar",
    "empeza": "empezar",
    # terminar
    "termina": "terminar",
    # finalizar
    "finaliza": "finalizar",
    # parar
    "parame": "parar",
    # detener
    "deten": "detener",
    "detene": "detener",
    # repetir
    "repite": "repetir",
    "repeti": "repetir",
    "repiteme": "repetir",
    "repetime": "repetir",
    # reintentar
    "reintenta": "reintentar",
}


def resolver_verbo(token: str) -> str | None:
    """Devuelve el infinitivo de `token` (directo o via VARIANTES_VERBO), o None."""
    if token in VERBOS_ACCION:
        return token
    return VARIANTES_VERBO.get(token)
